Doandinhduong/Areas/Admin/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;
namespace Doandinhduong.Areas.Admin.Controllers
{
    public class FooterController : BaseController
    {
        //
        // GET: /Admin/Footer/

        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new FooterDao();
            var model = dao.ListAllPaing(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int id)
        {
            var footer = new FooterDao().ViewDetail(id);

            return View(footer);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Footer footer) // Tạo tài khoản
        {
            if (ModelState.IsValid)
            {
                var dao = new FooterDao();
                long id = dao.Insert(footer);
                if (id > 0)
                {
                    return RedirectToAction("Index", "Footer");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm không thành công");
                }
            }
            return View("Index");

        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Footer footer)
        {
            if (ModelState.IsValid)
            {
                var dao = new FooterDao();
                var result = dao.Update(footer);
                if (result)
                {
                    return RedirectToAction("Index", "Footer");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật không thành công");
                }
            }
            return View("Index");

        }
        [HttpDelete]

        public ActionResult Delete(int id)
        {
            new FooterDao().Delete(id);
            return RedirectToAction("Index");
        }

    }

}

Doandinhduong/Controllers/LoginRegisterController.cs
using BotDetect.Web.Mvc;
using BotDetect.Web.UI;
using Doandinhduong.Areas.Admin.Common;
using Doandinhduong.Common;
using Doandinhduong.Models;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Doandinhduong.Controllers
{
    public class LoginRegisterController : Controller
    {
        //
        // GET: /LoginRegister/
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
       
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {

                var dao = new NguoidungDao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLoginSS();
                    userSession.UserName = user.Taikhoan;
                    userSession.UserID = user.ID_Nguoidung;
                    

                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    return RedirectToAction("/");
                }
                else if (result == 0 || result == -2)
                {
                    ModelState.AddModelError("", "Đăng nhập không đúng.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đã bị khóa.");
                }
            }
            return View("Login");
        }
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
        [HttpPost]
        [CaptchaValidation("CaptchaCode", "registerCapcha", "Mã xác nhận không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new NguoidungDao();
                if (dao.CheckUserName(model.Taikhoan))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new Nguoidung();
                    user.Taikhoan = model.Taikhoan;
                    user.Matkhau = Encryptor.MD5Hash(model.Matkhau);
                    user.Email = model.Email;
                    user.ID_MuctieuNguoidung = 1;
                    user.ID_Kieunguoi = 1;
                    user.Status = true;
                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View(model);
        }
    }
}

Doandinhduong/Views/Shared/Footer.cshtml
@model Model.EF.Footer
<div class="col-md-6">
    <div class="col-md-3 w3_footer_grid">
    <h3>Thông tin</h3>
    <ul class="w3_footer_grid_list">
        <li><a href="">Trang chủ</a></li>
        <li><a href="">Giới thiệu</a></li>
        <li><a href="">Kiến thức dinh dưỡng</a></li>
        <li><a href="">Công cụ</a></li>
    </ul>
    </div>
</div>

    <div class="agile_footer_grids">
        <div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
            <div class="w3_footer_grid_bottom">
                <h5>connect with us</h5>
                <ul class="agileits_social_icons">
                    <li><a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>        
    </div>

Doandinhduong/Views/Shared/MainMenu.cshtml
@model List<Model.EF.Menu>
<div class="logo_products">
    <div style="background:white">
        <div class="container">

            <div class="w3ls_logo_products_left">
                <a href="/"><img src="/Asset/client/images/logodinhduong.png" class="imglogo" /></a>
            </div>
            <div class="w3ls_logo_products_left1">
                <ul class="special_items">
                    @foreach (var item in Model)
                    {
                        <li><a href="@item.Link">@item.Text</a><i>/</i></li>
                    }

                </ul>
            </div>
        </div>


        <div class="clearfix"> </div>
    </div>
</div>

Doandinhduong/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
@{
    var session = (Doandinhduong.Areas.Admin.Common.UserLoginSS)Session[Doandinhduong.Common.CommonConstants.USER_SESSION];
}
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Sức khỏe là vàng</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="/Asset/client/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/Asset/client/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome icons -->
    <link href="/Asset/client/css/font-awesome.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/Asset/client/css/jquery-ui.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
    <!-- //font-awesome icons -->
    <!-- js -->
    <script src="/Asset/client/js/jquery-1.11.1.min.js"></script>
    <!-- //js -->
    <link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="/Asset/client/js/move-top.js"></script>
    <script type="text/javascript" src="/Asset/client/js/easing.js"></script>
    <script src="/Asset/client/js/jquery-ui.js"></script>
    <link href="/Asset/client/cssfix/fixfont.css" rel="stylesheet" />
    <script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
    </script>
    <!-- start-smoth-scrolling -->
</head>

<body>
    <!-- header -->
    <div class="agileits_header">
        <div class="w3l_offers">
            @if (session == null)
            {
                <a href="/gianh-cho-ban" class="goodforyou">Giành cho bạn!</a>
            }
            else
            {
                
                <a href="/gianh-cho-ban/@session.UserName" class="goodforyou">Giành cho bạn!</a>
            }
            
        </div>
        <div class="w3l_search">
            <form action="/tim-kiem" method="get">
                <input type="text" id="txtKeyword" name="keyword" value="" onfocus="this.value = '';"  placeholder=" tìm kiếm thực phẩm..." />
                <input type="submit" value=" ">
            </form>
        </div>
       
        <div class="w3l_header_right">
            <ul>
                
                @if (session == null)
                {
                    <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
                    <div class="mega-dropdown-menu">
                        <div class="w3ls_vegetables">
                            <ul class="dropdown-menu drp-mnu">
                                <li><a href="/dang-nhap">Đăng nhập</a></li>
                                <li><a href="/dang-ky">Đăng ký</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                }
                else
                {
                    
                    <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
                    <div class="mega-dropdown-menu">
                        <div class="w3ls_vegetables">
                            <ul class="dropdown-menu drp-mnu">
                                <li>Xin chào:@session.UserName</li>
                                <li>@Html.ActionLink("Thông tin cá nhân", "ThongtinNguoidung", "Nguoidung", new { id = @session.UserID }, new AjaxOptions { HttpMethod = "GET" })</li>
                                <li>@Html.ActionLink("Thoát", "Logout", "LoginRegister")</li>
                            </ul>
                        </div>
                    </div>
                </li>
                }

                
            </ul>
        </div>
        <div class="w3l_header_right1">
            <h2><a href="/lien-he">Liên hệ</a></h2>
        </div>
        <div class="clearfix"> </div>
    </div>
    <!-- script-for sticky-nav -->
    <script>
	$(document).ready(function() {
		 var navoffeset=$(".agileits_header").offset().top;
		 $(window).scroll(function(){
			var scrollpos=$(window).scrollTop();
			if(scrollpos >=navoffeset){
				$(".agileits_header").addClass("fixed");
			}else{
				$(".agileits_header").removeClass("fixed");
			}
		 });

	});
    </script>
    <!-- //script-for sticky-nav -->
    @{Html.RenderAction("MainMenu", "Home");}
    <!-- //header -->
    <!-- banner -->
    @RenderBody()
    <!-- footer -->
    <div class="footer">
        <div class="container">
            @{Html.RenderAction("Footer", "Home");}
        </div>
    </div>
    <!-- //footer -->
    <!-- Bootstrap Core JavaScript -->
    <script src="/Asset/client/js/bootstrap.min.js"></script>
    <script>
$(document).ready(function(){
    $(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');
        }
    );
});
    </script>
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
    </script>
    <!-- //here ends scrolling icon -->
    <script src="/Asset/client/js/minicart.js"></script>
    <script>
		paypal.minicart.render();

		paypal.minicart.cart.on('checkout', function (evt) {
			var items = this.items(),
				len = items.length,
				total = 0,
				i;

			// Count the number of each item in the cart
			for (i = 0; i < len; i++) {
				total += items[i].get('quantity');
			}

			if (total < 3) {
				alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
				evt.preventDefault();
			}
		});

    </script>
    <script src="/Asset/client/js/controller/baseController.js"></script>
    <script src="/Asset/client/js/controller/userController.js"></script>
    <script src="~/Asset/client/js/controller/ChartController.js"></script>

    <script src="~/Asset/client/js/controller/Chart.min.js"></script>
    <link href="/Asset/client/cssfix/fixbody.css" rel="stylesheet" />
    @RenderSection("fixstyle", required: false)

</body>
</html>