Doandinhduong/Controllers/LienheController.cs
using Common;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Doandinhduong.Controllers
{
    public class LienheController : Controller
    {
        //
        // GET: /Lienhe/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Guimail(string Name, string mobile, string address, string Email, string Message)
        {
            try
            {
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Asset/client/template/maillienhe.html"));

                content = content.Replace("{{CustomerName}}", Name);
                content = content.Replace("{{Phone}}", mobile);
                content = content.Replace("{{Email}}", Email);
                content = content.Replace("{{Address}}", address);
                content = content.Replace("{{Message}}", Message);
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                
                new MailHelper().SendMail(toEmail, "Lời nhắn", content);
            }
            catch (Exception ex)
            {
                //ghi log
                return Redirect("Index");
            }
            return Redirect("Index");
        }

    }
}

Doandinhduong/Views/Lienhe/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="fresh-vegetables">
    <div class="container">
        <div class="w3l_fresh_vegetables_grids">
            <div class="mail">
                <h3>Mail Us</h3>
                <div class="agileinfo_mail_grids">
                    <div class="col-md-4 agileinfo_mail_grid_left">
                        <ul>
                            <li><i class="fa fa-home" aria-hidden="true"></i></li>
                            <li>Địa chỉ<span>Linh trung, Thủ đức</span></li>
                        </ul>
                        <ul>
                            <li><i class="fa fa-envelope" aria-hidden="true"></i></li>
                            <li>email<span><a href="mailto:info@example.com">tranthanhvan236@gmail.com</a></span></li>
                        </ul>
                        <ul>
                            <li><i class="fa fa-phone" aria-hidden="true"></i></li>
                            <li>Điện thoại: <span>(+84)1642973279</span></li>
                        </ul>
                    </div>
                    <div class="col-md-8 agileinfo_mail_grid_right">
                        @using (Html.BeginForm("Guimail", "Lienhe", FormMethod.Post))
                        {
                            <div class="col-md-6 wthree_contact_left_grid">
                                <input type="text" name="Name" value="Name*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Tên*';}" required="">
                                <input type="email" name="Email" value="Email*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email*';}" required="">
                            </div>
                            <div class="col-md-6 wthree_contact_left_grid">
                                <input type="text" name="mobile" value="mobile*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Điện thoại*';}" required="">
                                <input type="text" name="address" value="address*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Địa chỉ*';}" required="">                               
                            </div>
                            <div class="clearfix"> </div>
                            <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Lời nhắn...';}" required="">Lời nhắn...</textarea>
                           
                            <button type="submit" class="btn">Gửi</button>
                            <input type="reset" value="Hủy">
                        }
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link href="~/Asset/client/cssfix/fixstyle.css" rel="stylesheet" />